"""Nulrimok Strategy Pinned Constants"""

STRATEGY_ID = "NULRIMOK"

# Timing (KST)
DSE_START, DSE_END = (8, 0), (8, 30)
IEPE_START, IEPE_END = (9, 10), (15, 10)
FLOW_EXIT_CHECK_START = (8, 55)  # Start loop before 09:00 for flow reversal exits
FLOW_EXIT_START = (9, 0, 5)  # Avoid first 5 seconds of session
FLOW_EXIT_END = (9, 1, 0)  # Execute flow reversal exits in 55-second window
BAR_INTERVAL_MIN = 30

# Regime Weights
REGIME_PRICE_WEIGHT, REGIME_BREADTH_WEIGHT = 0.25, 0.30
REGIME_VOL_WEIGHT, REGIME_FX_WEIGHT = 0.25, 0.20
REGIME_TIER_A_THRESHOLD, REGIME_TIER_B_THRESHOLD = 0.65, 0.40
BREADTH_THRESHOLD, VOL_PERCENTILE_CAP, FX_CHANGE_CAP = 0.55, 0.90, 0.02

# Sector
SECTOR_FLOW_WEIGHT, SECTOR_BREADTH_WEIGHT, SECTOR_PART_WEIGHT = 0.45, 0.30, 0.25
SECTOR_RANK_1, SECTOR_RANK_2, SECTOR_RANK_3, SECTOR_RANK_OTHER = 1.0, 0.8, 0.6, 0.3

# Flow Score
FLOW_PERSISTENCE_WEIGHT, FLOW_INTENSITY_WEIGHT, FLOW_ACCEL_WEIGHT = 0.40, 0.35, 0.25
FLOW_PERSISTENCE_MIN = 0.6

# Leader Filter
LEADER_TIER_A_PCT, LEADER_TIER_B_PCT = 60, 70

# AVWAP
AVWAP_BAND_PCT, AVWAP_ACCEPTANCE_PCT = 0.005, 0.01
ANCHOR_LOOKBACK_DAYS, ANCHOR_MIN_STREAK, IMPULSE_VOL_MULT = 40, 5, 2.0

# Entry
ENTRY_DIP_SMA_PERIOD, ENTRY_VOL_DRYUP_PCT, CONFIRM_BARS = 5, 0.60, 2

# Exit
AVWAP_BREAKDOWN_PCT, BREAKDOWN_VOL_MULT, RECLAIM_BARS = 0.007, 1.5, 5
TIME_STOP_INTRADAY_PNL, TIME_STOP_MULTI_DAYS, TIME_STOP_MULTI_PNL = 0.0, 2, 0.01

# Ranking/Sizing
DAILY_RANK_FLOW_WEIGHT, DAILY_RANK_LEADER_WEIGHT = 0.40, 0.20
DAILY_RANK_SECTOR_WEIGHT, DAILY_RANK_AVWAP_WEIGHT = 0.20, 0.20
SIZE_TOP_20_MULT, SIZE_20_50_MULT, SIZE_50_80_MULT = 1.5, 1.0, 0.7
SECTOR_CAP_PCT, INTRADAY_VOL_BONUS = 0.30, 1.10  # Aligned with OMS max_sector_pct
MAX_RISK_PCT = 0.005 * 1.65  # Cap total multiplier at 0.825% of equity
FLOW_EXIT_REPRICE_TIMEOUT_SEC = 30  # Reprice unfilled flow reversal exits after 30s

# Active Set
ACTIVE_SET_K = 30
ROTATION_INTERVAL_MIN = 60
TRADABLE_TIER_A_PCT, TRADABLE_TIER_B_PCT = 0.30, 0.20
